services:
  postgres:
    image: postgres:15-alpine
    container_name: db-postgres
    environment:
      POSTGRES_DB: db-password-change-this
      POSTGRES_USER: db-user-change-this
      POSTGRES_PASSWORD: db-password-change-this
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U db-user-change-this -d db-password-change-this",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: